# RunSH Configuration
# Examples:
#   scripts_dir: './scripts'  # Local directory
#   scripts_dir: 'https://github.com/user/repo/tree/main/scripts'  # GitHub

default_shell: bash
scripts_dir: https://github.com/crimson206/my-scripts/tree/main/scripts/temp
